name: hcaptcha_solver
description: Dart port of [go-captcha](https://github.com/JustTalDevelops/go-hcaptcha).
version: 0.0.8
repository: https://github.com/j4qfrost/hcaptcha_solver-dart.git
homepage: https://j4qfrost.github.io

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  bezier: ^1.2.0
  dart_jsonwebtoken: ^2.8.2
  http: ^1.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^1.4.0
  puppeteer: ^3.1.1
  vector_math: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.0.0
  test: ^1.21.0
